sudo: required
services:
    - docker 
before_install:
    - docker build -t varunchillara/dockerreactapp -f Dockerfile.dev .
script:
    - docker run varunchillara/dockerreactapp npm run test -- --coverage
